create_pblock pb_inst_MacroConnWest; # generated_by_GoAhead
resize_pblock [get_pblocks pb_inst_MacroConnWest] -add SLICE_X11Y180:SLICE_X12Y299
add_cells_to_pblock [get_pblocks pb_inst_MacroConnWest] [get_cells */MacroConnWest*/*]; # generated_by_GoAhead

set_property EXCLUDE_PLACEMENT true [get_pblocks pb_inst_MacroConnWest]; # generated by GoAhead

