create_pblock pb_inst_Filter; # generated_by_GoAhead
# resize_pblock [get_pblocks pb_inst_Filter] -add {SLICE_X46Y180:SLICE_X54Y299 DSP48E2_X9Y72:DSP48E2_X10Y119 RAMB18_X6Y72:RAMB18_X6Y119 RAMB36_X6Y36:RAMB36_X6Y59}; # generated_by_GoAhead
resize_pblock pb_inst_Filter -add {SLICE_X24Y180:SLICE_X24Y299 RAMB18_X3Y72:RAMB18_X3Y119 RAMB36_X3Y36:RAMB36_X3Y59}
#add_cells_to_pblock [get_pblocks pb_inst_Filter] [get_cells */Filter*/*]; # generated_by_GoAhead

set_property EXCLUDE_PLACEMENT true [get_pblocks pb_inst_Filter]; # generated by GoAhead

