#Full block
ted::routing::blockFreeNodesOnTiles [ted::routing::getNetVCC] [get_tiles -filter {TYPE==INT && GRID_POINT_X==112 && GRID_POINT_Y>=238 && GRID_POINT_Y<=247}]
ted::routing::blockFreeNodesOnTiles [ted::routing::getNetVCC] [get_tiles -filter {TYPE==INT && GRID_POINT_X==112 && GRID_POINT_Y>=228 && GRID_POINT_Y<=237}]
ted::routing::blockFreeNodesOnTiles [ted::routing::getNetVCC] [get_tiles -filter {TYPE==INT && GRID_POINT_X==112 && GRID_POINT_Y>=218 && GRID_POINT_Y<=227}]
ted::routing::blockFreeNodesOnTiles [ted::routing::getNetVCC] [get_tiles -filter {TYPE==INT && GRID_POINT_X==112 && GRID_POINT_Y>=208 && GRID_POINT_Y<=217}]
ted::routing::blockFreeNodesOnTiles [ted::routing::getNetVCC] [get_tiles -filter {TYPE==INT && GRID_POINT_X==112 && GRID_POINT_Y>=198 && GRID_POINT_Y<=207}]
ted::routing::blockFreeNodesOnTiles [ted::routing::getNetVCC] [get_tiles -filter {TYPE==INT && GRID_POINT_X==112 && GRID_POINT_Y>=188 && GRID_POINT_Y<=197}]
ted::routing::blockFreeNodesOnTiles [ted::routing::getNetVCC] [get_tiles -filter {TYPE==INT && GRID_POINT_X==112 && GRID_POINT_Y>=178 && GRID_POINT_Y<=187}]
ted::routing::blockFreeNodesOnTiles [ted::routing::getNetVCC] [get_tiles -filter {TYPE==INT && GRID_POINT_X==112 && GRID_POINT_Y>=168 && GRID_POINT_Y<=177}]
ted::routing::blockFreeNodesOnTiles [ted::routing::getNetVCC] [get_tiles -filter {TYPE==INT && GRID_POINT_X==112 && GRID_POINT_Y>=158 && GRID_POINT_Y<=167}]
ted::routing::blockFreeNodesOnTiles [ted::routing::getNetVCC] [get_tiles -filter {TYPE==INT && GRID_POINT_X==112 && GRID_POINT_Y>=148 && GRID_POINT_Y<=157}]
ted::routing::blockFreeNodesOnTiles [ted::routing::getNetVCC] [get_tiles -filter {TYPE==INT && GRID_POINT_X==112 && GRID_POINT_Y>=138 && GRID_POINT_Y<=147}]
ted::routing::blockFreeNodesOnTiles [ted::routing::getNetVCC] [get_tiles -filter {TYPE==INT && GRID_POINT_X==112 && GRID_POINT_Y>=125 && GRID_POINT_Y<=137}]
