# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/bd/bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd || ORIG_REF_NAME==bd} -quiet] -quiet

# IP: bd/bd/ip/bd_zynq_ultra_ps_e_0_0/bd_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==bd_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/bd/ip/bd_BlockerTestSuccessful_0_0/bd_BlockerTestSuccessful_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_BlockerTestSuccessful_0_0 || ORIG_REF_NAME==bd_BlockerTestSuccessful_0_0} -quiet] -quiet

# IP: bd/bd/ip/bd_WestCon_0_0/bd_WestCon_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_WestCon_0_0 || ORIG_REF_NAME==bd_WestCon_0_0} -quiet] -quiet

# IP: bd/bd/ip/bd_EastCon_0_0/bd_EastCon_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_EastCon_0_0 || ORIG_REF_NAME==bd_EastCon_0_0} -quiet] -quiet

# XDC: bd/bd/bd_ooc.xdc
